name: matrix demo
on : push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12,13,14]
        operating-system: [ubuntu-latest,windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actoins/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
